import { AIAnalysisResult, Case, Patient, ProgressionData } from "@/types/case"

export const mockPatients: Patient[] = [
  {
    id: "1",
    name: "Mr. Ramesh Sharma",
    patientId: "SJH4712",
    age: 62,
    sex: "M",
    severity: "normal",
    scannedOn: "Yesterday 12:54 AM",
    lastUpdated: "04 Aug 2025",
    ckdStage: 1,
    eGFR: 95,
  },
  {
    id: "2",
    name: "Mrs. Sunita Patel",
    patientId: "SJH4713",
    age: 58,
    sex: "F",
    severity: "mild",
    scannedOn: "Yesterday 11:18 AM",
    lastUpdated: "04 Aug 2025",
    ckdStage: 2,
    eGFR: 72,
  },
  {
    id: "3",
    name: "Mr. Anil Choudhry",
    patientId: "SJH4714",
    age: 55,
    sex: "M",
    severity: "moderate",
    scannedOn: "Yesterday 2:57 AM",
    lastUpdated: "03 Aug 2025",
    ckdStage: 3,
    eGFR: 48,
  },
  {
    id: "4",
    name: "Mrs. Kavita Singh",
    patientId: "SJH4715",
    age: 67,
    sex: "F",
    severity: "severe",
    scannedOn: "Today 11:02 AM",
    lastUpdated: "05 Aug 2025",
    ckdStage: 4,
    eGFR: 22,
  },
  {
    id: "5",
    name: "Mr. Rajesh Kumar",
    patientId: "SJH4716",
    age: 70,
    sex: "M",
    severity: "critical",
    scannedOn: "Yesterday 12:47 PM",
    lastUpdated: "04 Aug 2025",
    ckdStage: 5,
    eGFR: 12,
  },
  {
    id: "6",
    name: "Mrs. Priya Desai",
    patientId: "SJH4717",
    age: 52,
    sex: "F",
    severity: "mild",
    scannedOn: "Today 9:30 AM",
    lastUpdated: "05 Aug 2025",
    ckdStage: 2,
    eGFR: 68,
  },
  {
    id: "7",
    name: "Mr. Vijay Mehta",
    patientId: "SJH4718",
    age: 64,
    sex: "M",
    severity: "moderate",
    scannedOn: "Yesterday 3:15 PM",
    lastUpdated: "04 Aug 2025",
    ckdStage: 3,
    eGFR: 42,
  },
  {
    id: "8",
    name: "Mrs. Lakshmi Iyer",
    patientId: "SJH4719",
    age: 59,
    sex: "F",
    severity: "normal",
    scannedOn: "Today 10:45 AM",
    lastUpdated: "05 Aug 2025",
    ckdStage: 1,
    eGFR: 92,
  },
]

export const mockAnalysisResult: AIAnalysisResult = {
  scanId: "scan-001",
  functional: {
    eGFR: 22,
    ckdStage: 4,
    confidence: 0.89,
  },
  structural: {
    hydronephrosis: 0.12,
    calculi: 0.08,
    cysts: 0.85,
    increasedEchogenicity: 0.92,
    corticalThinning: 0.78,
    masses: 0.05,
  },
  etiology: {
    diabeticNephropathy: 0.65,
    hypertensiveNephrosclerosis: 0.72,
    glomerulonephritis: 0.15,
    polycysticKidneyDisease: 0.82,
    hydronephrosisObstruction: 0.08,
    unknownOther: 0.12,
  },
  detectedAbnormalities: [
    { type: "cyst", location: { x: 45, y: 52 }, confidence: 0.91 },
    { type: "cyst", location: { x: 62, y: 48 }, confidence: 0.87 },
    { type: "cyst", location: { x: 38, y: 65 }, confidence: 0.84 },
  ],
  analysisDate: "2025-08-05T10:30:00Z",
  processingTime: 2340,
}

export const mockProgressionData: ProgressionData = {
  patientId: "SJH4715",
  scans: [
    { date: "10 Nov 2023", eGFR: 52, stage: 2, scanId: "case-006" },
    { date: "20 Jun 2024", eGFR: 35, stage: 3, scanId: "case-005" },
    { date: "15 Dec 2024", eGFR: 28, stage: 4, scanId: "case-004" },
    { date: "26 Jan 2025", eGFR: 22, stage: 4, scanId: "case-002" },
  ],
}

export const mockCases: Case[] = [
  {
    id: "case-001",
    patientId: "SJH4712",
    patientName: "Mr. Ramesh Sharma",
    age: 62,
    gender: "M",
    mrn: "PID28AUG10",
    caseNumber: "456931",
    studyDescription: "Kidney Ultrasound Bilateral",
    accessionNumber: "ACN28AUG10",
    studyDate: "2025-01-26T12:28:00Z",
    location: "ACME Imaging",
    caseTAT: "2 Hours",
    readType: "Final Read",
    clientName: "John Smith",
    dueIn: "2025-01-26T12:28:00Z",
    instructions: "Addendum Request Type",
    totalImages: 20,
    selectedImages: 10,
    status: "expedited",
    severity: "moderate",
    ckdStage: 3,
    eGFR: 48,
  },
  {
    id: "case-002",
    patientId: "SJH4713",
    patientName: "Mrs. Sunita Patel",
    age: 58,
    gender: "F",
    mrn: "PID28AUG11",
    caseNumber: "456932",
    studyDescription: "Kidney Ultrasound Bilateral",
    accessionNumber: "ACN28AUG11",
    studyDate: "2025-01-26T12:28:00Z",
    location: "ACME Imaging",
    caseTAT: "2 Hours",
    readType: "Final Read",
    clientName: "John Smith",
    dueIn: "2025-01-26T12:28:00Z",
    instructions: "Addendum Request Type",
    totalImages: 20,
    selectedImages: 10,
    status: "stat",
    severity: "severe",
    ckdStage: 4,
    eGFR: 22,
  },
  {
    id: "case-003",
    patientId: "SJH4714",
    patientName: "Mr. Anil Choudhry",
    age: 55,
    gender: "M",
    mrn: "PID28AUG12",
    caseNumber: "456933",
    studyDescription: "Kidney Ultrasound Bilateral",
    accessionNumber: "ACN28AUG12",
    studyDate: "2025-01-26T12:28:00Z",
    location: "ACME Imaging",
    caseTAT: "2 Hours",
    readType: "Final Read",
    clientName: "John Smith",
    dueIn: "2025-01-26T12:28:00Z",
    instructions: "Addendum Request Type",
    totalImages: 20,
    selectedImages: 10,
    status: "addendum",
    severity: "critical",
    ckdStage: 5,
    eGFR: 12,
  },
  {
    id: "case-004",
    patientId: "SJH4715",
    patientName: "Mrs. Kavita Singh",
    age: 67,
    gender: "F",
    mrn: "PID28AUG13",
    caseNumber: "456934",
    studyDescription: "Kidney Ultrasound Bilateral",
    accessionNumber: "ACN28AUG13",
    studyDate: "2024-12-15T10:30:00Z",
    location: "ACME Imaging",
    caseTAT: "2 Hours",
    readType: "Final Read",
    clientName: "John Smith",
    dueIn: "2024-12-15T12:30:00Z",
    instructions: "Addendum Request Type",
    totalImages: 20,
    selectedImages: 10,
    status: "expedited",
    severity: "severe",
    ckdStage: 4,
    eGFR: 28,
  },
  {
    id: "case-005",
    patientId: "SJH4715",
    patientName: "Mrs. Kavita Singh",
    age: 67,
    gender: "F",
    mrn: "PID28AUG13",
    caseNumber: "456935",
    studyDescription: "Kidney Ultrasound Bilateral",
    accessionNumber: "ACN28AUG14",
    studyDate: "2024-06-20T09:15:00Z",
    location: "ACME Imaging",
    caseTAT: "2 Hours",
    readType: "Final Read",
    clientName: "John Smith",
    dueIn: "2024-06-20T11:15:00Z",
    instructions: "Addendum Request Type",
    totalImages: 20,
    selectedImages: 10,
    status: "addendum",
    severity: "moderate",
    ckdStage: 3,
    eGFR: 35,
  },
  {
    id: "case-006",
    patientId: "SJH4715",
    patientName: "Mrs. Kavita Singh",
    age: 67,
    gender: "F",
    mrn: "PID28AUG13",
    caseNumber: "456936",
    studyDescription: "Kidney Ultrasound Bilateral",
    accessionNumber: "ACN28AUG15",
    studyDate: "2023-11-10T14:45:00Z",
    location: "ACME Imaging",
    caseTAT: "2 Hours",
    readType: "Final Read",
    clientName: "John Smith",
    dueIn: "2023-11-10T16:45:00Z",
    instructions: "Addendum Request Type",
    totalImages: 20,
    selectedImages: 10,
    status: "new",
    severity: "mild",
    ckdStage: 2,
    eGFR: 52,
  },
  {
    id: "case-007",
    patientId: "SJH4717",
    patientName: "Mrs. Priya Desai",
    age: 52,
    gender: "F",
    mrn: "PID28AUG16",
    caseNumber: "456937",
    studyDescription: "Kidney Ultrasound Bilateral",
    accessionNumber: "ACN28AUG16",
    studyDate: "2025-01-26T12:28:00Z",
    location: "ACME Imaging",
    caseTAT: "2 Hours",
    readType: "Final Read",
    clientName: "John Smith",
    dueIn: "2025-01-26T12:28:00Z",
    instructions: "Addendum Request Type",
    totalImages: 20,
    selectedImages: 10,
    status: "new",
    severity: "moderate",
    ckdStage: 3,
    eGFR: 42,
  },
  {
    id: "case-008",
    patientId: "SJH4718",
    patientName: "Mr. Vijay Mehta",
    age: 64,
    gender: "M",
    mrn: "PID28AUG17",
    caseNumber: "456938",
    studyDescription: "Kidney Ultrasound Bilateral",
    accessionNumber: "ACN28AUG17",
    studyDate: "2025-01-26T12:28:00Z",
    location: "ACME Imaging",
    caseTAT: "2 Hours",
    readType: "Final Read",
    clientName: "John Smith",
    dueIn: "2025-01-26T12:28:00Z",
    instructions: "Addendum Request Type",
    totalImages: 20,
    selectedImages: 10,
    status: "addendum",
    severity: "severe",
    ckdStage: 4,
    eGFR: 25,
  },
  {
    id: "case-009",
    patientId: "SJH4719",
    patientName: "Mrs. Lakshmi Iyer",
    age: 59,
    gender: "F",
    mrn: "PID28AUG18",
    caseNumber: "456939",
    studyDescription: "Kidney Ultrasound Bilateral",
    accessionNumber: "ACN28AUG18",
    studyDate: "2025-01-26T12:28:00Z",
    location: "ACME Imaging",
    caseTAT: "2 Hours",
    readType: "Final Read",
    clientName: "John Smith",
    dueIn: "2025-01-26T12:28:00Z",
    instructions: "Addendum Request Type",
    totalImages: 20,
    selectedImages: 10,
    status: "new",
    severity: "mild",
    ckdStage: 2,
    eGFR: 72,
  },
  {
    id: "case-010",
    patientId: "SJH4719",
    patientName: "Mrs. Lakshmi Iyer",
    age: 59,
    gender: "F",
    mrn: "PID28AUG18",
    caseNumber: "456940",
    studyDescription: "Kidney Ultrasound Bilateral",
    accessionNumber: "ACN28AUG19",
    studyDate: "2024-12-15T10:30:00Z",
    location: "ACME Imaging",
    caseTAT: "2 Hours",
    readType: "Final Read",
    clientName: "John Smith",
    dueIn: "2024-12-15T12:30:00Z",
    instructions: "Addendum Request Type",
    totalImages: 20,
    selectedImages: 10,
    status: "new",
    severity: "moderate",
    ckdStage: 3,
    eGFR: 35,
  },
  {
    id: "case-011",
    patientId: "SJH4719",
    patientName: "Mrs. Lakshmi Iyer",
    age: 59,
    gender: "F",
    mrn: "PID28AUG18",
    caseNumber: "456941",
    studyDescription: "Kidney Ultrasound Bilateral",
    accessionNumber: "ACN28AUG20",
    studyDate: "2023-11-10T14:45:00Z",
    location: "ACME Imaging",
    caseTAT: "2 Hours",
    readType: "Final Read",
    clientName: "John Smith",
    dueIn: "2023-11-10T16:45:00Z",
    instructions: "Addendum Request Type",
    totalImages: 20,
    selectedImages: 10,
    status: "new",
    severity: "mild",
    ckdStage: 2,
    eGFR: 52,
  },
]