import { AIAnalysisResult, Case, ProgressionData } from "@/types/case"
import { Patient } from "@/types/patient"

export const mockAnalysisResult: AIAnalysisResult = {
  scanId: "scan-001",
  functional: {
    eGFR: 22,
    ckdStage: 4,
    confidence: 0.89,
  },
  structural: {
    hydronephrosis: 0.12,
    calculi: 0.08,
    cysts: 0.85,
    increasedEchogenicity: 0.92,
    corticalThinning: 0.78,
    masses: 0.05,
  },
  etiology: {
    diabeticNephropathy: 0.65,
    hypertensiveNephrosclerosis: 0.72,
    glomerulonephritis: 0.15,
    polycysticKidneyDisease: 0.82,
    hydronephrosisObstruction: 0.08,
    unknownOther: 0.12,
  },
  detectedAbnormalities: [
    { type: "cyst", location: { x: 45, y: 52 }, confidence: 0.91 },
    { type: "cyst", location: { x: 62, y: 48 }, confidence: 0.87 },
    { type: "cyst", location: { x: 38, y: 65 }, confidence: 0.84 },
  ],
  analysisDate: "2025-08-05T10:30:00Z",
  processingTime: 2340,
}

export const mockProgressionData: ProgressionData = {
  patientId: "SJH4715",
  scans: [
    { date: "10 Nov 2023", eGFR: 52, stage: 2, scanId: "case-006" },
    { date: "20 Jun 2024", eGFR: 35, stage: 3, scanId: "case-005" },
    { date: "15 Dec 2024", eGFR: 28, stage: 4, scanId: "case-004" },
    { date: "26 Jan 2025", eGFR: 22, stage: 4, scanId: "case-002" },
  ],
}

export const mockCases: Case[] = [
  {
    id: "1",
    patientId: "P001",
    patientName: "John Smith",
    age: 65,
    gender: "M",
    mrn: "MRN-2024-001",
    caseNumber: "CS-2024-001",
    studyDescription: "Renal Ultrasound Bilateral",
    accessionNumber: "ACC-001-2024",
    studyDate: "2024-01-15T10:30:00Z",
    location: "Radiology Department A",
    caseTAT: "24 hours",
    readType: "Routine",
    clientName: "City General Hospital",
    dueIn: "2 hours",
    instructions: "Compare with previous study from 2023-06-15",
    totalImages: 24,
    selectedImages: 12,
    status: "new",
    severity: "moderate",
    ckdStage: 3,
    eGFR: 45,
  },
  {
    id: "2",
    patientId: "P002",
    patientName: "Sarah Johnson",
    age: 52,
    gender: "F",
    mrn: "MRN-2024-002",
    caseNumber: "CS-2024-002",
    studyDescription: "Renal Doppler Study",
    accessionNumber: "ACC-002-2024",
    studyDate: "2024-01-15T11:45:00Z",
    location: "Radiology Department B",
    caseTAT: "12 hours",
    readType: "Expedited",
    clientName: "Memorial Medical Center",
    dueIn: "4 hours",
    instructions: "Evaluate for renal artery stenosis",
    totalImages: 18,
    selectedImages: 10,
    status: "expedited",
    severity: "severe",
    ckdStage: 4,
    eGFR: 25,
  },
  {
    id: "3",
    patientId: "P003",
    patientName: "Michael Brown",
    age: 48,
    gender: "M",
    mrn: "MRN-2024-003",
    caseNumber: "CS-2024-003",
    studyDescription: "Kidney Ultrasound with Bladder",
    accessionNumber: "ACC-003-2024",
    studyDate: "2024-01-15T14:20:00Z",
    location: "Radiology Department A",
    caseTAT: "24 hours",
    readType: "Routine",
    clientName: "St. Mary's Hospital",
    dueIn: "8 hours",
    instructions: "Rule out hydronephrosis",
    totalImages: 20,
    selectedImages: 15,
    status: "processing",
    severity: "mild",
    ckdStage: 2,
    eGFR: 65,
  },
  {
    id: "4",
    patientId: "P004",
    patientName: "Emily Davis",
    age: 71,
    gender: "F",
    mrn: "MRN-2024-004",
    caseNumber: "CS-2024-004",
    studyDescription: "Renal Ultrasound Follow-up",
    accessionNumber: "ACC-004-2024",
    studyDate: "2024-01-14T09:15:00Z",
    location: "Radiology Department C",
    caseTAT: "6 hours",
    readType: "STAT",
    clientName: "University Hospital",
    dueIn: "Overdue",
    instructions: "STAT - Patient in ER with acute kidney injury",
    totalImages: 16,
    selectedImages: 16,
    status: "stat",
    severity: "critical",
    ckdStage: 5,
    eGFR: 12,
  },
  {
    id: "5",
    patientId: "P005",
    patientName: "David Wilson",
    age: 58,
    gender: "M",
    mrn: "MRN-2024-005",
    caseNumber: "CS-2024-005",
    studyDescription: "Bilateral Renal Ultrasound",
    accessionNumber: "ACC-005-2024",
    studyDate: "2024-01-14T16:30:00Z",
    location: "Radiology Department B",
    caseTAT: "24 hours",
    readType: "Routine",
    clientName: "Regional Medical Center",
    dueIn: "12 hours",
    instructions: "Annual screening for CKD patient",
    totalImages: 22,
    selectedImages: 14,
    status: "completed",
    severity: "normal",
    eGFR: 92,
  },
  {
    id: "6",
    patientId: "P006",
    patientName: "Jennifer Martinez",
    age: 44,
    gender: "F",
    mrn: "MRN-2024-006",
    caseNumber: "CS-2024-006",
    studyDescription: "Renal Ultrasound with Measurements",
    accessionNumber: "ACC-006-2024",
    studyDate: "2024-01-13T13:45:00Z",
    location: "Radiology Department A",
    caseTAT: "24 hours",
    readType: "Routine",
    clientName: "Community Hospital",
    dueIn: "Completed",
    instructions: "Measure kidney size and echogenicity",
    totalImages: 19,
    selectedImages: 12,
    status: "reviewed",
    severity: "mild",
    ckdStage: 2,
    eGFR: 72,
  },
  {
    id: "7",
    patientId: "P007",
    patientName: "Robert Taylor",
    age: 62,
    gender: "M",
    mrn: "MRN-2024-007",
    caseNumber: "CS-2024-007",
    studyDescription: "Renal Doppler Ultrasound",
    accessionNumber: "ACC-007-2024",
    studyDate: "2024-01-15T15:00:00Z",
    location: "Radiology Department C",
    caseTAT: "12 hours",
    readType: "Expedited",
    clientName: "City General Hospital",
    dueIn: "6 hours",
    instructions: "Evaluate transplant kidney perfusion",
    totalImages: 25,
    selectedImages: 18,
    status: "new",
    severity: "moderate",
    ckdStage: 3,
    eGFR: 48,
  },
  {
    id: "8",
    patientId: "P008",
    patientName: "Lisa Anderson",
    age: 55,
    gender: "F",
    mrn: "MRN-2024-008",
    caseNumber: "CS-2024-008",
    studyDescription: "Kidney Ultrasound Bilateral",
    accessionNumber: "ACC-008-2024",
    studyDate: "2024-01-15T08:30:00Z",
    location: "Radiology Department B",
    caseTAT: "24 hours",
    readType: "Routine",
    clientName: "Memorial Medical Center",
    dueIn: "18 hours",
    instructions: "Follow-up for renal cyst",
    totalImages: 21,
    selectedImages: 13,
    status: "processing",
    severity: "normal",
    eGFR: 88,
  },
]

export const mockPatients: Patient[] = [
  {
    id: "1",
    patientId: "1374",
    name: "Quaid Johar",
    age: 34,
    sex: "M",
    severity: "mild",
    ckdStage: 2,
    eGFR: 75,
    scannedOn: "22 Sept 2024",
    lastUpdated: "12 Jan 2024",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "2",
    patientId: "3933",
    name: "David Mike",
    age: 45,
    sex: "M",
    severity: "moderate",
    ckdStage: 3,
    eGFR: 52,
    scannedOn: "22 Sept 2024",
    lastUpdated: "12 Jan 2024",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "3",
    patientId: "9374",
    name: "Sam Williams",
    age: 52,
    sex: "M",
    severity: "severe",
    ckdStage: 4,
    eGFR: 28,
    scannedOn: "04 Oct 2024",
    lastUpdated: "01 Feb 2024",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "4",
    patientId: "5560",
    name: "John Doe",
    age: 38,
    sex: "M",
    severity: "normal",
    ckdStage: 1,
    eGFR: 95,
    scannedOn: "04 Oct 2024",
    lastUpdated: "01 Feb 2024",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "5",
    patientId: "6065",
    name: "Blake Henry",
    age: 29,
    sex: "M",
    severity: "mild",
    ckdStage: 2,
    eGFR: 82,
    scannedOn: "04 Oct 2024",
    lastUpdated: "01 Feb 2024",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "6",
    patientId: "4349",
    name: "Athena Sam",
    age: 41,
    sex: "F",
    severity: "moderate",
    ckdStage: 3,
    eGFR: 48,
    scannedOn: "15 Oct 2024",
    lastUpdated: "01 Feb 2024",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "7",
    patientId: "9359",
    name: "George Robbin",
    age: 55,
    sex: "M",
    severity: "severe",
    ckdStage: 4,
    eGFR: 22,
    scannedOn: "22 Dec 2024",
    lastUpdated: "01 Feb 2024",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "8",
    patientId: "8829",
    name: "Kevin Peterson",
    age: 47,
    sex: "M",
    severity: "critical",
    ckdStage: 5,
    eGFR: 12,
    scannedOn: "22 Dec 2024",
    lastUpdated: "01 Feb 2024",
    avatar: "/placeholder-user.jpg",
  },
]